export const VIDEO_TEMPLATES = [
  {
    id: 'tpl-viral-short',
    name: '爆款短视频',
    tag: '🔥 热门',
    category: '短视频',
    ratio: '9:16',
    duration: 30,
    style: '黄金3秒爆款钩子',
    prompt: '制作一个30秒高留存爆款短视频，开场3秒强钩子，节奏紧凑，适合抖音/小红书',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    creditsCost: 120,
  },
  {
    id: 'tpl-xhs-grass',
    name: '小红书种草',
    tag: '🔥 热门',
    category: '种草',
    ratio: '3:4',
    duration: 45,
    style: '商业故事 / 案例拆解',
    prompt: '制作小红书风格种草视频，真实体验感+产品亮点+购买理由，语气亲切',
    thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
    creditsCost: 150,
  },
  {
    id: 'tpl-knowledge-ip',
    name: '知识 IP 口播',
    tag: '⭐ 推荐',
    category: '知识',
    ratio: '16:9',
    duration: 60,
    style: '专业干货 / 深度解析',
    prompt: '制作知识博主口播视频，结构清晰：问题-方法-案例-总结，适合 B 站/视频号',
    thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80',
    creditsCost: 180,
  },
  {
    id: 'tpl-product-launch',
    name: '产品宣传',
    tag: '商业',
    category: '品牌',
    ratio: '16:9',
    duration: 45,
    style: '专业干货 / 深度解析',
    prompt: '制作 SaaS 产品宣传视频，突出核心价值、使用场景与客户收益',
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80',
    creditsCost: 200,
  },
  {
    id: 'tpl-ai-tech',
    name: 'AI 科技解读',
    tag: '科技',
    category: '科技干货',
    ratio: '9:16',
    duration: 30,
    style: '专业干货 / 深度解析',
    prompt: '解读 AI 技术趋势对普通人的影响，语言通俗，画面科技感强',
    thumbnail: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80',
    creditsCost: 120,
  },
  {
    id: 'tpl-course-teaser',
    name: '课程预告片',
    tag: '教育',
    category: '教育',
    ratio: '16:9',
    duration: 60,
    style: '商业故事 / 案例拆解',
    prompt: '制作在线课程预告片，展示课程大纲、讲师背书、学习收益与限时优惠',
    thumbnail: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80',
    creditsCost: 160,
  },
]
